version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "./bin/api"
    ports:
      - "8081:8081"
  envoy:
    image: envoyproxy/envoy:v1.21.6
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - api
